const {test,expect}=require('@playwright/test');
const jwt=require('jsonwebtoken');
const {database,seed}=require('./helpers/trial-funnel-fixture');
test.describe('local Vercel trial journey with real APIs and PostgreSQL',()=>{
  test.skip(process.env.TRIAL_FUNNEL_PREVIEW!=='1','Requires scripts/prepare-trial-funnel-preview.js and local Vercel at port 3107.');
  test.describe.configure({mode:'serial'});
  test.use({serviceWorkers:'block'});
  let pool,sql,fixture;
  test.beforeAll(async()=>{({pool,sql}=database());fixture=await seed(sql,'browser-'+Date.now());await sql`DELETE FROM rate_limits`;});
  test.afterAll(async()=>{if(pool)await pool.end();});
  test('campaign clean URL → free booking API → confirmation → profile correction → instructor preparation → aggregate report',async({page,context,request,baseURL})=>{
    test.setTimeout(120000);
    expect(baseURL).toBe('http://localhost:3107');
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.route(/^https:\/\//,route=>route.fulfill({status:204,body:''}));
    await page.addInitScript(()=>localStorage.setItem('cc_cookie_consent',JSON.stringify({analytics:false,marketing:false,version:2,timestamp:new Date().toISOString()})));
    const landing=await page.goto('/test-booked');expect(landing.status()).toBe(200);
    expect(landing.headers()['content-security-policy']).toContain("script-src 'self'");
    await expect(page.locator('video')).toHaveCount(0);
    await page.locator('[data-trial-placement="hero"]').click();
    await expect(page).toHaveURL(/\/free\?campaign=test_booked_v1/);
    // Keep the same campaign context, constrain the real slot feed to the fixture instructor.
    await page.goto('/free?campaign=test_booked_v1&instructor_id='+fixture.instructorId);
    await expect(page.locator('#trialTestDetails')).toBeVisible();
    await page.locator('.slot-btn').first().click();
    const suffix=String(Date.now()).slice(-8),email='preview-'+suffix+'@example.invalid';
    for(const [id,value]of Object.entries({guest_name:'Preview learner',guest_email:email,guest_phone:'079'+suffix,guest_pickup_address:'Isolated preview pickup'}))await page.locator('#'+id).fill(value);
    await page.locator('#trialTestBooked').selectOption('yes');await page.locator('#trialTestDate').fill(fixture.date);await page.locator('#trialTestCentre').fill('Original preview centre');
    const response=page.waitForResponse(r=>r.url().includes('action=book-free-trial'));
    await page.getByRole('button',{name:'Book my free trial'}).click();expect((await response).status()).toBe(200);
    await expect(page).toHaveURL(/free-trial-success\.html/);
    await expect(page.getByRole('link',{name:'Add or update your practical test details'})).toBeVisible();
    const [intake]=await sql`SELECT t.* FROM trial_booking_intakes t JOIN learner_users lu ON lu.id=t.learner_id AND lu.school_id=t.school_id WHERE t.school_id=1 AND lu.email=${email}`;
    expect(intake).toBeTruthy();
    expect(intake).toMatchObject({entry_page:'test_booked',test_centre_snapshot:'Original preview centre',analytics_consent_at_booking:false});
    const secret='isolated-trial-funnel-fixture-secret';
    await context.addCookies([{name:'cc_learner',value:jwt.sign({id:intake.learner_id,role:'learner',school_id:1},secret),url:baseURL,httpOnly:true},{name:'cc_csrf',value:'fixture',url:baseURL}]);
    await page.evaluate(id=>localStorage.setItem('cc_learner',JSON.stringify({user:{id,name:'Preview learner',school_id:1}})),intake.learner_id);
    await page.getByRole('link',{name:'Add or update your practical test details'}).click();
    await expect(page.locator('#testCentre')).toHaveValue('Original preview centre',{timeout:20000});
    await page.locator('#testBooked').selectOption('no');await page.getByRole('button',{name:'Save details'}).click();
    await expect(page.locator('#saveStatus')).toContainText('Details saved');
    const instructorToken=jwt.sign({id:fixture.instructorId,role:'instructor',school_id:1},secret);
    const prepResponse=await request.get('/api/instructor?action=learner-notes&learner_id='+intake.learner_id,{headers:{cookie:'cc_instructor='+instructorToken}});
    expect(prepResponse.status()).toBe(200);const prep=await prepResponse.json();
    expect(prep.current_test_details.booked).toBe(false);expect(prep.trial_intake.test_centre_snapshot).toBe('Original preview centre');
    const now=new Date(),from=now.toISOString().slice(0,10);now.setUTCDate(now.getUTCDate()+1);const to=now.toISOString().slice(0,10);
    const adminToken=jwt.sign({id:1,role:'admin',school_id:1},secret);
    const reportResponse=await request.get('/api/admin?action=trial-funnel-report&from='+from+'&to='+to,{headers:{cookie:'cc_admin='+adminToken}});
    expect(reportResponse.status()).toBe(200);const report=await reportResponse.json();expect(report.ok).toBe(true);
    expect(JSON.stringify(report)).not.toContain(email);expect(JSON.stringify(report)).not.toContain('Original preview centre');
    const denied=await request.get('/api/admin?action=trial-funnel-report&from='+from+'&to='+to);expect(denied.status()).toBe(401);
    await page.reload();expect(await sql`SELECT id FROM trial_booking_intakes WHERE school_id=1 AND booking_id=${intake.booking_id}`).toHaveLength(1);
    await context.addCookies([{name:'cc_admin',value:adminToken,url:baseURL,httpOnly:true}]);
    await page.evaluate(()=>localStorage.setItem('cc_admin',JSON.stringify({admin:{id:1,name:'Isolated admin',school_id:1}})));
    await page.goto('/admin/learner-controls.html');
    await page.locator('#trial-funnel-panel summary').click();
    await page.locator('#trial-report-from').fill(from);await page.locator('#trial-report-to').fill(to);
    await page.getByRole('button',{name:'Load report'}).click();
    await expect(page.locator('#trial-report-result')).toContainText('No all-product paid-hours headline',{timeout:20000});
    const download=page.waitForEvent('download');await page.locator('#trial-report-csv').click();
    const artifact=await download;expect(artifact.suggestedFilename()).toBe('trial-funnel-'+from+'.csv');
    const csv=require('fs').readFileSync(await artifact.path(),'utf8');
    expect(csv).toContain('definition_version');expect(csv).toContain('as_of');expect(csv).not.toContain(email);
    await page.setViewportSize({width:375,height:812});await page.goto('/test-booked');
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await expect(page.locator('.mobile-cta')).toBeVisible();
    await page.screenshot({path:require('path').join(require('os').tmpdir(),'trial-funnel-mobile-final.png'),fullPage:true});
    await page.setViewportSize({width:1365,height:900});
    await page.screenshot({path:require('path').join(require('os').tmpdir(),'trial-funnel-desktop-final.png'),fullPage:true});
    expect(errors).toEqual([]);
  });
});
